language: node_js

node_js:
  - 6
  - 6.0
  - 6.1
  - 6.2
  - 6.3
  - 6.4
  - 6.5
  - 6.6
  - 6.7
  - 6.8
  - 6.9
  - 6.10
  - 6.11
  - 7
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 7.5
  - 7.6
  - 7.7
  - 7.8
  - 7.9
  - 7.10
  - 8
  - 8.0
  - 8.1
